### ISSUE TITLE
Duplicar engranajes

### ISSUE THREAD

**Issue by ghost** [Proyectos1-FDI-UCM/c2223-Grupo09#10]
### **Duplicar engranajes**
______________________________________

### Descripción
Puede recolectar engranajes reiniciando niveles (incluidos los niveles de prueba donde no se muestra la interfaz).
Así, el juego se puede completar con un escudo casi infinito, siendo invulnerable.

### Pasos
1.	Iniciar un nivel de prueba (con engranajes)
2.	Colectarlas
3.	Reiniciar nivel
4.	Repetir puntos 1-3 
5.	Usar escudo o curar HP muchas veces.

**Comment by Javalonso1** [comment]
Solucionado
