### ISSUE TITLE
La cámara está temblando

### ISSUE THREAD

**Issue by ghost** [Proyectos1-FDI-UCM/c2223-Grupo09#11]
### **La cámara está temblando**
______________________________________

### Descripción
En el nivel con la habitación oculta y la caja que podemos mover, si el jugador se para en el centro del nivel y corre de izquierda a derecha (A-D), la cámara comienza a temblar.

### Pasos
1.	Iniciar un nivel con caja y habitación oculta.
2.	Pararse en el centro del nivel.
3.	Correr (usando los botones A-D).

**Comment by Javalonso1** [comment]
No es un error crítico que impida jugar al juego
