### ISSUE TITLE
Salto en caída

### ISSUE THREAD

**Issue by PedroSanchezVela06** [Proyectos1-FDI-UCM/c2223-Grupo09#12]
### Descripción
Hace un salto pequeño si se salta antes de tocar el suelo, como si se le aplicara la fuerza de salto durante la caída anulando esta. Este segundo salto es mayor en las cajas. 
### Pasos
Paso 1: Salta.
Paso 2: Vuelve a saltar justo antes de tocar el suelo.
Paso 3: Hacer lo mismo pero encima de una caja.

### Video
https://user-images.githubusercontent.com/123490291/235121626-01577789-29bb-4dff-8198-4fc0b01e1edd.mp4

**Comment by Javalonso1** [comment]
Solucionado?
