### ISSUE TITLE
Salto con caja

### ISSUE THREAD

**Issue by PedroSanchezVela06** [Proyectos1-FDI-UCM/c2223-Grupo09#13]
### Descripción

Al estar pegado del lado izquierdo de la caja el personaje se impulsa mucho hacia arriba como si saltara varias veces.

### Pasos

Paso 1: Ponerte cerca del lado izquierdo de una caja.
Paso 2: Pulsa el botón de salto mientras te mueves hacia la esquina izquierda de la caja.
Paso 3: Volver a saltar justo al pasar por la esquina izquierda de la caja.

### Video

https://user-images.githubusercontent.com/123490291/235123127-fb7f837b-5b15-4a25-82e9-d276616cfeb9.mp4

**Comment by Javalonso1** [comment]
Solucionado
