### ISSUE TITLE
Escudo no funciona

### ISSUE THREAD

**Issue by PedroSanchezVela06** [Proyectos1-FDI-UCM/c2223-Grupo09#14]
### Descripción

Si te golpea y activas el escudo te pueden seguir golpeando aunque tengas el escudo activo.
De hecho no puedes activar otro.

### Pasos

Paso 1: Dejate golpear por un proyectil.
Paso 2: Activa el escudo.
Paso 3: Vuelvete a dejar golpear.

### Video

https://user-images.githubusercontent.com/123490291/235124885-a49c7976-a96a-412e-b41a-1d506ac0f794.mp4

**Comment by Javalonso1** [comment]
Arreglado
