### ISSUE TITLE
No se puede hacer el dash en el aire si saltas mientras corres

### ISSUE THREAD

**Issue by DiegoAlonsoValenciano** [Proyectos1-FDI-UCM/c2223-Grupo09#5]
## Nombre del error

No se puede hacer el dash en el aire si saltas mientras corres

### Descripción

Cuando estás corriendo y saltas no puedes realizar el dash

### Pasos

1.   Paso 1: Corre
2.   Paso 2: Salta mientras corres
3.   Paso 3: Usa el dash mientras estas en el aire
4.   Paso 4: no hace el dash

### Captura de pantalla o vídeo
![error dash](https://user-images.githubusercontent.com/125390412/235117996-02d05aa2-fb75-4d4a-96d3-42494c990558.jpg)
Si corres y saltas no te hace el dash en el aire

**Comment by Javalonso1** [comment]
A nosotros nos funciona bien
