### ISSUE TITLE
Las puertas están cerradas

### ISSUE THREAD

**Issue by ghost** [Proyectos1-FDI-UCM/c2223-Grupo09#7]
### **Las puertas están cerradas**
______________________________________

### Descripción
En los niveles tutorial y normal (excepto el Boss final), la salida no funciona. Las puertas están cerradas, es imposible pasar al siguiente nivel.

### Pasos
1.	Completar todas las tareas de nivel (matar a todos los enemigos, recoger engranajes).
2.	Acercarse a la salida

**Comment by Javalonso1** [comment]
Solucionado
