### ISSUE TITLE
No guarda HP

### ISSUE THREAD

**Issue by ghost** [Proyectos1-FDI-UCM/c2223-Grupo09#8]
### **No guarda HP**
______________________________________

### Descripción
Cantidad de HP en constante cambio. El indicador de HP puede desaparecer después de reiniciar el juego. O puede guardar cantidad de HP (1-2 corazones) y repetirlo en cada nivel. 

### Pasos
1.	Tomar daño en cualquier nivel.
2.	Salir (Esc – Menu)
3.	Empezar otro nivel

**Comment by Javalonso1** [comment]
Solucionado
